// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function FetchRepos(arg1:string):Promise<Array<main.Repository>>;

export function SetVisibilityBatch(arg1:string,arg2:Array<string>,arg3:boolean):Promise<Array<main.BatchResult>>;
